version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://root:example@mongo:27017/nuhoud?authSource=admin
    depends_on:
      - mongo
    command: ["node", "dist/main"]

volumes:
  mongo_data:
